### ISSUE TITLE
Reporting the wrong culprit 

### ISSUE THREAD

**Issue by kakaroto** [Moerill/fvtt-find-the-culprit#1]
Hey, this module is genius! Absolutely great, but it has one big flaw : it didn't give me the actual culprit :(
I tried it today to try and figure out which module was causing an issue, and a couple of usability issues : 
- I didn't notice the "X modules remaining" in the window title until the very end
- I'd like to see something similar to `git bisect` which says how many steps are remaining
- When the list of remaining candidates is, let's say, smaller than 10 or 20, I'd like to know what that list is, so if I can mentally eliminate most of them, that can save me a few painful reloads

Other than the usability issues mentioned above, the big issue is that it reported the wrong culprit. After I don't know how many reloads I did and painfully testing the specific use case, it gives me "the culprit is X" and that result made no sense, I tested with that module alone and the issue wasn't there, so I had to redo the whole process but manually this time to find the actual culprit.
This may be a off-by-one issue, or a 'using-the-wrong-set' or something, but yeah, it wasn't reliable :(
If it had shown the last few candidates, that would have made it easier for me to test afterwards, instead of doing it all over from scratch.

**Comment by Moerill** [comment]
Ups, ye i seem to have made some mistake somewhere, when i got hacky and just wanted to finish this :see_no_evil:
I think i have fixed it now!
 
Fixed it and added all of your suggestions, although i always show all modules in a small, scrollable subwindow.
