### ISSUE TITLE
Foundry VTT Warning

### ISSUE THREAD

**Issue by brunocalado** [Moerill/fvtt-find-the-culprit#20]
Hi

Can you remove the foundry warning? 
![image](https://user-images.githubusercontent.com/4999783/148289615-af321ec4-b13f-4db2-b4f3-d9bbdf29519f.png)

Just replace in module.json with this:
`  "compatibleCoreVersion": "9"`
or 
`  "compatibleCoreVersion": "10"`

**Comment by CaosFR** [comment]
Same for me, please update :)

**Comment by Moerill** [comment]
Changed it on the foundry package page. That should be enough (i think?)
if it is still there, send me a PR if you want to get it fixed "fast". I'm currently to busy to work on my modules and such i'm not touching them (besides accepting PRs)

**Comment by brunocalado** [comment]
yes, until next build
![image](https://user-images.githubusercontent.com/4999783/150119090-7e52a757-50b4-4c4d-a934-f209172fe44c.png)

**Comment by brunocalado** [comment]
https://github.com/Moerill/fvtt-find-the-culprit/pull/22
