### ISSUE TITLE
FoundryVTT V10 compatibility?

### ISSUE THREAD

**Issue by gsterling** [Moerill/fvtt-find-the-culprit#28]
Will you update this module for V10? It just disabled all my modules with no way to reenable them through the module itself.

I have some problems with V10 and want to know which modules are causing it. But with over 100 modules and multiple problems I don't see how I would be able without your module.

**Comment by imobe001** [comment]
@gsterling I've been running into this to.....however, a work-around is to hit "F5" to manually refresh the page.  Seems to sort of work as the automatic refresh doesn't work.

**Comment by gsterling** [comment]
> @gsterling I've been running into this to.....however, a work-around is to hit "F5" to manually refresh the page. Seems to sort of work as the automatic refresh doesn't work.

I tried that and it started the process of disabling all my modules and asked me, if the problem persists. When I said it doesn't it didn't offer me to enable some modules. When I pressed F5 again, the dialog was completely gone and I had to reenable all modules by hand.

**Comment by multiplenerdgasms** [comment]
I'm in the same boat. When I attempt to use Find the Culprit, it has me select the module(s) I want to keep active, but things do not progress beyond that point.

**Comment by Moerill** [comment]
There was a fix provided by arcanist, which i finally got around merging. Sorry for the trouble.
I hope this fixes your issues, if not please comment on this issue and i'll reopen it.
