### ISSUE TITLE
No refresh

### ISSUE THREAD

**Issue by CaosFR** [Moerill/fvtt-find-the-culprit#29]
Hi

Thanks for your module, since last update if I active your module automatic refresh (for example on/off a module) dont work. I have to F5. I have try just with your module (no other module on).

Thanks for your help.

**Comment by MrPotatoZed** [comment]
Seeing the same behavior here. When changing what modules are active hitting save module settings the page will not refresh without f5 or hitting refresh on the browser. Very rarely I've seen it refresh as it should but 8 or 9 times out of ten it won't refresh without manual action. Tested with only FTC active. De-activating FTC fixes the behavior. Seeing the following error in console when I click on save module settings:
![unknown-2](https://user-images.githubusercontent.com/85974617/189787842-9530ce35-8be6-4cf2-8426-2191c58d596a.png)
v9.280, 5e 1.6.3, FTC 1.4.2. Hosted on the forge. Tested in chrome. 

Thanks for your work on this.

**Comment by thatlonelybugbear** [comment]
Same v9.280, 5e 1.6.3, FTC 1.4.2, local hosting

**Comment by arcanistzed** [comment]
Oh no. This update was my contribution. The fix I implemented is for v10 only. I'll see if I can sort this out shortly.

**Comment by MrPotatoZed** [comment]
1.4.3 seems to be working great. Thank you!

**Comment by Zamrod** [comment]
This update seems to have broken V10. It now doesn't refresh anymore
