### ISSUE TITLE
Please add a "stop debugging and reactivate mods" button

### ISSUE THREAD

**Issue by jacobjorvang** [Moerill/fvtt-find-the-culprit#3]

**Comment by maplealmond** [comment]
Very important if the module gets into a weird state.  I am currently dealing with "0 modules still in lsit, remaining steps infinity" which is has rendered the module unusuable without clearing it out.

**Comment by Moerill** [comment]
Added this.
Though i'd be kinda interested in how you encountered "0 modules still in list". If you have steps to reproduce that, please add an issue for it! (Although i got a small fix for that in the next patch as well, so that shouldn#t happen again)
