### ISSUE TITLE
This update seems to have broken V10. It now doesn't refresh anymore

### ISSUE THREAD

**Issue by Zamrod** [Moerill/fvtt-find-the-culprit#31]
This update seems to have broken V10. It now doesn't refresh anymore

_Originally posted by @Zamrod in https://github.com/Moerill/fvtt-find-the-culprit/issues/29#issuecomment-1248823362_

**Comment by arcanistzed** [comment]
Fixed by fada700bec0aab1e00975db1252415f7b0f6f29d
